version: '3.8'

services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extras-addons
      - odoo-web-data:/var/lib/odoo
    command: odoo -i itbpress_b2b --load-language=en_US

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  alpine:
    image: alpine:latest
    depends_on:
      - db
      - web
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./dump:/backup

volumes:
  odoo-web-data:
    name: odoo-web-data
  odoo-db-data:
    name: odoo-db-data
